### ISSUE TITLE
left sidebar breaks on long text

### ISSUE THREAD

**Issue by mfelsche** [ponylang/mkdocs-theme#5]
## Description
The left sidebar moves the sign for collapsed or uncollapsed submenu to the next line, because the sidebar is too small.

![auswahl_001](https://user-images.githubusercontent.com/1152667/40564152-e6fd8cb4-6067-11e8-8081-3af43219da9d.png)

### Expected behavior

Have the sidebar overflow.

### System information

* OS: Ubuntu 16.04
* Browser: Firefox 60.0.1

**Comment by EpicEric** [comment]
Got it to look a bit better with the following rule:

```css
label.md-nav__link {
  white-space: nowrap;
}
```

![image](https://user-images.githubusercontent.com/3129194/65839809-38379400-e2e7-11e9-9344-697e65e88ce1.png) ![image](https://user-images.githubusercontent.com/3129194/65839820-44bbec80-e2e7-11e9-848b-66aa08887144.png)

Is something like this what you had in mind? @mfelsche

**Comment by mfelsche** [comment]
yes, neat trick! Looking forward to the PR. :)

**Comment by aturley** [comment]
@EpicEric can you open a PR for this?
