### ISSUE TITLE
Remove temporary fix for tornado dependency.

### ISSUE THREAD

**Issue by jemc** [ponylang/mkdocs-theme#7]
@malthe called out [here](https://github.com/ponylang/mkdocs-theme/commit/5ae15f02bc057548de24e9007e9d551740ebee17#r30632874) that the temporary fix in that commit for the `tornado` dependency can now be removed.

**Comment by SeanTAllen** [comment]
how do we test that? we make the change, publish it then hope that nothing goes wrong on release?

**Comment by jemc** [comment]
I'm honestly not sure - I don't know much about this repo and how it works. I just wanted to capture @malthe's comment in a more permanent space (an issue ticket).

**Comment by SeanTAllen** [comment]
@mfelsche can you handle this once https://github.com/ponylang/ponyc/pull/2903 has been merged?

In the directions:

```
Distribution

Upload to PyPI with Twine:

rm dist/*
python setup.py sdist bdist_wheel
twine upload dist/*
```

is that what is supposed to be done to upload a new version?

**Comment by mfelsche** [comment]
I can and will handle this on monday.

For creating a new version you also need to update the version in the setup.py file and then run the commands above. I'll add a more clear description to the readme.

**Comment by SeanTAllen** [comment]
This has been fixed on master. Needs to be released.
